name: 🐍 Release

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "Action Type"
        required: true
        default: "Download"
        type: choice
        options:
          - Download
          - Upload

jobs:
  release:
    name: 🐍 Release
    runs-on: windows-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v2

      - name: 🔵 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: 📄 Generate config_variables.py
        run: |
          # echo "ACTION_TYPE = '${{ inputs.action_type }}'" > src/config/config_variables.py
          # echo "GCLOUD_PATH = '${{ env.GCLOUD_PATH }}'" >> src/config/config_variables.py
          cat .env

      - name: ⏬ Install Dependencies
        run: |
          ls src -Force
          pip install pyinstaller==6.14.2
          pip install flet==0.24.1

      - name: 🔧 Build exe file
        run: |
          pip install .
          python -m PyInstaller --onefile --hidden-import "flet" --hidden-import "dotenv" --noconfirm --add-data ".env;." main.py

      - name: ⬆️ Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.action_type }}
          path: ./dist
