name: 🐍 Release

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "Action Type"
        required: true
        default: "Download"
        type: choice
        options:
          - Download
          - Upload

jobs:
  release:
    name: 🐍 Release
    runs-on: windows-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v2

      - name: 🔵 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: ⏬ Install Dependencies
        run: |
          pip install pyinstaller==6.14.2
          pip install flet==0.24.1

      - name: 🔧 Build exe file
        run: |
          pip install .
          python -m PyInstaller --onefile --hidden-import "flet" --hidden-import "dotenv" --noconfirm main.py
      
      - name: 📂 Check current directory
        run: Get-ChildItem -Force | Select-Object Name, Attributes, @{Name="Permissions";Expression={(Get-Acl $_.FullName).AccessToString}}

      
      - name: 🚚 Copy .env
        run: |
          echo "hello"
          ls -Force ./dist
          echo "hello"
          cp .env ./dist/
          echo "hello"
          ls -Force ./dist
          echo "hello"

      - name: ⬆️ Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.action_type }}
          path: ${{ github.workspace }}/dist
