name: 🐍 Release

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "Action Type"
        required: true
        default: "Download"
        type: choice
        options:
          - Download
          - Upload

jobs:
  release:
    name: 🐍 Release
    runs-on: windows-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v2

      - name: 🔵 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: ⏬ Install Dependencies
        run: |
          pip install pyinstaller==6.14.2
          pip install flet==0.24.1

      - name: 🔧 Build exe file
        run: |
          pip install .
          python -m PyInstaller --onefile --hidden-import "flet" --hidden-import "dotenv" --noconfirm main.py
      
      - name: 🚚 Copy .env
        run: |
          Copy-Item -Path ".env" -Destination "./dist/"

      - name: 💫 Extract actionType
        id: action_type
        run: |
          $envFile = Get-Content .env
          $actionType = $envFile | Where-Object { $_ -match '^ACTION_TYPE=' } | ForEach-Object { $_.Split('=')[1].Trim('"') }
          echo "::set-output name=actionType::$actionType"

      - name: ⬆️ Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.action_type.outputs.actionType }}"
          include-hidden-files: true
          path: ./dist
